### ISSUE TITLE
Replace Livereload by BrowserSync ?

### ISSUE THREAD

**Issue by zckrs** [driftyco/ionic-app-lib#1]
Hi, 

What do you think about replace LiveReload by BrowerSync ? 

BrowserSync have more usefull features : 
* interaction sync = scroll, click, refresh and form actions are mirrored between browsers while you test
* a configuration panel 

This library can be very beneficial for development.
You should have a look. 

http://www.browsersync.io/
https://github.com/BrowserSync/browser-sync
[Comparison between Livereload, BrowserSync, Codekit](http://www.slant.co/topics/1479/compare/~browsersync_vs_livereload_vs_codekit)

Are you against this idea ? 
I would like to contribute to add BrowserSync.

**Comment by jbavari** [comment]
I'm not opposed to it at all. At the current time, I don't have much time allocated to that feature (yet).

In the meantime though, throw together a PR and I'd be happy to review it!

**Comment by Telemakhos** [comment]
+1 for browser-sync

**Comment by tlancina** [comment]
We did this and it caused problems for windows users, the issue I believe being that browsersync requires Visual Studio (or recommends, hopefully there is something smaller one can install).

Closing as a wontfix for now, if there is less of a drastic requirement for windows in the future we can reopen.

**Comment by yura-pakhuchiy** [comment]
@tlancina it looks like it does not require full visual studio install, but only  Visual C++ Redistributable Packages. It can be downloaded from here: https://www.microsoft.com/en-us/download/details.aspx?id=40784
Could you re-evaluate this issue?

source: https://github.com/BrowserSync/browser-sync/issues/665

**Comment by yura-pakhuchiy** [comment]
BTW, this library only 7 MB for x64 and many of windows programs install different versions of it.

**Comment by MartinMuzatko** [comment]
Agreed @yura-pakhuchiy. it might be worth to have another look @tlancina.
