### ISSUE TITLE
State.savePlugin fails to save variables for standard npm plugin

### ISSUE THREAD

**Issue by talamaska** [driftyco/ionic-app-lib#30]
So after a lot of research, I've found that in state.js
if the plugin is added by id and has variables, the script doesn't save the variables at all.
To test you can run ionic plugin add phonegap-facebook-plugin --variable APP_ID="xxxx" --variable APP_NAME="yyyy".
there are missing tests for this case which is strange.

the scripts checks if it's not local and immediately bypasses any check for variables.
There are strange thing in restore state too, 
for example the script checks for wrong tags in the config.xml in order to restore the variables.

function getPluginParameters. After running the restore state command on a correct package.json with facebook plugin variables, it deletes them.

**Comment by QuentinFchx** [comment]
I have the same issue. When you add a plugin by id, it does not save variables.
Could you advice on it @jbavari ?

**Comment by talamaska** [comment]
Well, that's why I have created this pull request. I think @jbavari should check this out, write jasmine tests and merge it. It doesn't look good when this is some old problem and nobody is looking at it, because everybody is focused on ionic 2.
