### ISSUE TITLE
[v2] google chrome is hardcoded in serve.js

### ISSUE THREAD

**Issue by sclausen** [driftyco/ionic-app-lib#37]
It won't work on different os like linux, which uses `google-chrome`, not `google chrome`

**Comment by tlancina** [comment]
This should be fixed in the latest `ionic@alpha`! Please reopen if it isn't :)

**Comment by sclausen** [comment]
I don't find the exact lines where this happens, but now it opens firefox per default and afaik its treated the same over different os :grin:

**Comment by sclausen** [comment]
@tlancina I don't find the exact lines where this happens, but now it opens firefox per default and afaik its treated the same over different os :grin:
