### ISSUE TITLE
lib/start.js - buffer size exceeded on OSX

### ISSUE THREAD

**Issue by mikkokam** [driftyco/ionic-app-lib#77]
After updating to latest ionic CLI, some users on OSX (at least) seem to fail to create new projects.
`ionic start projectname --v2 `
fails with 
`Unable to run exec commandError: stderr maxBuffer exceeded (CLI v2.0.0-beta.17)`

The default value of maxBuffer in Node.js is 200KB.

Going through the code at CLI, the actual buffer size problem can be tracked back to [ionic-app-lib/lib/start.js](https://github.com/driftyco/ionic-app-lib/blob/90b511d70485c36bf496f45596df94897edc31c6/lib/start.js)

At `Start.runExecCommand`, the childProcess.exec fills the buffer.

Testing with pumping up the buffer size:
`childProcess.exec(command, {maxBuffer: 10240 * 500}, function(err, stdout, stderr) {`
resolves this, and `ionic start` works again. For some reason, my first try at 1024 * 500 was not enough, had to be larger - then tested with the very large value of 10240 * 500 with success...
Quick fix is to pump up the buffer size, but maybe use spawn instead of exec, if this child process potentially returns a lot of data?

More discussion:
https://forum.ionicframework.com/t/ionic-v2-error-message-when-creating-project/42020/2

**Comment by tlancina** [comment]
Switched to spawn in the latest beta, thanks!
