### ISSUE TITLE
download error with phonegap app

### ISSUE THREAD

**Issue by cyptus** [driftyco/ionic-app-lib#8]
"ionic serve" together with the phonegap developer app ( http://app.phonegap.com/ ) is not working anymore on android and ios for me. i'm using the newest app and cli versions:

Cordova CLI: 5.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.5
OS: Windows 7 SP1
Node Version: v0.10.33

i have also installed the latest phonegap desktop app und phonegap cli with the version "5.0.0-0.28.1".

The app shows "Download Error" and a popup with "unable to download archive from the server".

in the ionic forum:
http://forum.ionicframework.com/t/ionic-serve-download-error-with-phonegap-app/27129

**Comment by jbavari** [comment]
I'm not familiar with the phonegap developer app, sorry.

There's not much help I can provide with that tool.

**Comment by jbavari** [comment]
I've been told by a colleague - "They might want to check the configuration used by phonegap. It may differ from the Cordova configuration.
