### ISSUE TITLE
Add windows platform to serve --lab

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-app-lib#86]
https://github.com/driftyco/ionic-app-lib/blob/master/lib/assets/preview.html

It would be nice to have windows platform displayed here, as well, but we should exclude it for v1 apps.

**Comment by tlancina** [comment]
Done in https://github.com/driftyco/ionic-app-lib/commit/87c5ff9206b4a8e32ae9deddbc94138bbf784af4.
